// CultBrand Briefing — Módulos y preguntas
// Exportable como módulo ES6

export const MODULES = {
  estrategia: {
    label:'Consultoría estratégica de marca', icon:'◎', questions:[
      {id:'e1',type:'radio',label:'¿Tenéis marca actualmente?',
        options:['Sí, activa y funcional','Sí, pero necesita revisión profunda','En proceso de creación','No existe todavía']},
      {id:'e2',type:'check',label:'¿Qué tipo de marca es?',hint:'Selecciona todo lo que aplique',
        options:['Marca corporativa','Marca de producto','Marca personal / profesional','Varias marcas / arquitectura de marca']},
      {id:'e3',type:'radio',label:'¿Habéis trabajado antes con una agencia o estudio de branding?',
        hint:'Nos ayuda a calibrar expectativas y el nivel de acompañamiento necesario',
        options:['Sí, con buena experiencia','Sí, con resultados mixtos','No, es la primera vez','Internamente, sin agencia externa']},
      {id:'e4',type:'textarea',label:'¿Cuál es el problema o situación que os ha traído aquí?',
        hint:'Sé directo. ¿Qué ha cambiado en el negocio o en el mercado?',
        placeholder:'Hemos crecido y nuestra imagen no nos representa, perdemos frente a competidores con marca más sólida...'},
      {id:'e5',type:'textarea',label:'¿Cuál es el objetivo principal de este proyecto?',
        placeholder:'Reposicionarnos, lanzar al mercado, unificar marcas, actualizar imagen...'},
      {id:'e6',type:'text',label:'¿En qué sector operáis y cuál es vuestro modelo de negocio?',
        placeholder:'Sector retail, B2B de servicios, startup SaaS...'},
      {id:'e7',type:'textarea',label:'¿Cuál es vuestra propuesta de valor? ¿En qué sois diferentes?',
        hint:'Si no lo tenéis definido todavía, indicadlo. Es información igualmente útil.',
        placeholder:'Somos los únicos que...'},
      {id:'e8',type:'textarea',label:'¿A quién os dirigís principalmente?',
        placeholder:'Empresas de 50-200 empleados en sector industrial, o consumidor final 25-40 años urbano...'},
      {id:'e9',type:'textarea',label:'Nombra 3-5 competidores directos y referencias que admiréis',
        placeholder:'Competidores: A, B, C. Marcas que inspiran aunque no sean del sector: X, Y...'},
      {id:'e10',type:'check',label:'¿Qué metodología de trabajo preferís?',
        hint:'Selecciona todo lo que aplique',
        options:['Workshop presencial','Workshop por videollamada','Entrevistas internas con el equipo','Panel de consumidores / focus group','Solo trabajo escrito / asíncrono']},
      {id:'e11',type:'radio',label:'¿Cuántas personas participarán activamente en el proceso?',
        hint:'Condiciona el alcance de workshops, entrevistas y rondas de validación',
        options:['1-2 personas (decisor directo)','3-5 personas (equipo reducido)','6-10 personas (varios departamentos)','Más de 10 personas']},
      {id:'e12',type:'radio',label:'¿Hay algún hito de negocio que ancle el proyecto a una fecha?',
        hint:'Lanzamiento de producto, feria, inauguración, ronda de inversión...',
        options:['Sí, hay una fecha límite inamovible','Sí, hay una fecha orientativa','No, el proyecto no está condicionado por fechas externas']},
      {id:'e13',type:'check',label:'¿En qué mercados operáis o queréis operar?',
        options:['Solo local / regional','España','Europa','Latinoamérica','Internacional / global']},
      {id:'e14',type:'radio',label:'Orientación de presupuesto',
        options:['Menos de 5.000 €','Entre 5.000 y 15.000 €','Entre 15.000 y 40.000 €','Más de 40.000 €','Prefiero no indicarlo ahora']}
    ]
  },
  identidad: {
    label:'Identidad visual y Brand Book', icon:'▣', questions:[
      {id:'i1',type:'radio',label:'¿Existe alguna identidad visual actualmente?',
        options:['Sí, completa y funcional','Sí, pero desactualizada o inconsistente','Solo tenemos logotipo','No existe nada todavía']},
      {id:'i2',type:'radio',label:'¿Tenéis el naming definitivo?',
        hint:'Si el nombre de marca está por decidir o hay dudas sobre él, el alcance cambia',
        options:['Sí, el nombre está cerrado y sin conflicto','El nombre está decidido pero no verificado legalmente','El nombre está en revisión o hay alternativas','No tenemos nombre definitivo todavía']},
      {id:'i3',type:'radio',label:'¿Qué alcance tiene este encargo?',
        options:['Creación desde cero','Evolución / actualización de la existente','Rediseño total','Solo un elemento concreto (logotipo, colores, tipografía...)']},
      {id:'i4',type:'textarea',label:'¿Hay activos existentes que debamos respetar o integrar?',
        hint:'Packaging producido, flota rotulada, señalética reciente... Condicionan lo que es realmente "rediseñable"',
        placeholder:'Tenemos 5.000 unidades de packaging ya impresas, una flota de 12 vehículos rotulados...'},
      {id:'i5',type:'check',label:'¿Dónde se aplicará la identidad?',hint:'Selecciona todo lo que aplique',
        options:['Web y digital','Redes sociales','Packaging','Señalética / entorno físico','Papelería corporativa','Uniformes','Publicidad exterior','Merchandising','Presentaciones internas']},
      {id:'i6',type:'check',label:'¿Qué estilo visual os atrae más?',hint:'Orientativo, no definitivo',
        options:['Minimalista y clean','Premium / lujo','Moderno y tecnológico','Cercano y humano','Orgánico / natural','Audaz y expresivo','Clásico y atemporal','Juvenil y dinámico']},
      {id:'i7',type:'textarea',label:'Referencias visuales que os gusten',
        hint:'Dentro o fuera de vuestro sector. Podéis pegar links.',
        placeholder:'Apple por su minimalismo, Innocent por el tono, Patagonia por los valores...'},
      {id:'i8',type:'textarea',label:'¿Hay colores, símbolos o estilos que definitivamente no queréis?',
        placeholder:'No queremos el rojo, evitar iconografía demasiado usada en el sector...'},
      {id:'i9',type:'radio',label:'¿Qué nivel de manual de marca necesitáis?',
        options:['Manual completo de identidad corporativa','Guía básica de uso (digital)','Solo especificaciones técnicas','No lo sé todavía']},
      {id:'i10',type:'check',label:'¿En qué formatos necesitáis los archivos?',
        options:['AI / Illustrator','PDF editable','Figma','PNG / SVG','Otros (lo indicamos en comentarios)']},
      {id:'i11',type:'radio',label:'¿Habéis trabajado antes con una agencia o estudio de diseño?',
        options:['Sí, con buena experiencia','Sí, con resultados mixtos','No, es la primera vez']}
    ]
  },
  campana: {
    label:'Campaña de publicidad', icon:'↗', questions:[
      {id:'c1',type:'radio',label:'¿Cuál es el objetivo principal de la campaña?',
        options:['Notoriedad / dar a conocer la marca','Posicionamiento / cambiar percepción','Lanzamiento de producto o servicio','Generar leads / conversiones','Fidelización y retención']},
      {id:'c2',type:'textarea',label:'¿Qué producto o servicio queremos comunicar?',
        hint:'Qué es, qué problema resuelve, cuál es su precio orientativo',
        placeholder:'Un nuevo servicio de suscripción para pymes que...'},
      {id:'c3',type:'textarea',label:'¿A quién va dirigida la campaña?',
        placeholder:'Directores de RRHH de empresas +100 empleados, madres de 30-45 años...'},
      {id:'c4',type:'textarea',label:'¿Cuál debe ser el mensaje clave que se lleva el receptor?',
        hint:'Si tenéis claim o concepto previo, indicadlo. Si no, describid la emoción o idea principal.',
        placeholder:'Que somos la marca que más entiende a los pequeños empresarios...'},
      {id:'c5',type:'radio',label:'¿Disponéis de material propio (imágenes, vídeo) o necesitáis producción desde cero?',
        hint:'Un anuncio con material de archivo es sustancialmente más económico que uno con rodaje propio',
        options:['Disponemos de material propio reutilizable','Tenemos algo pero necesitamos producción adicional','Producción desde cero','No lo hemos valorado todavía']},
      {id:'c6',type:'radio',label:'¿Hay una agencia de medios que gestione la compra de espacios?',
        hint:'Determina si CultBrand asume solo creatividad y producción, o también la planificación de medios',
        options:['Sí, tenemos agencia de medios propia','No, lo centralizamos todo en vosotros','No hacemos medios pagados','No lo hemos decidido todavía']},
      {id:'c7',type:'check',label:'¿En qué medios o canales queréis activar la campaña?',
        options:['Redes sociales (paid)','Display / programática','Search (Google Ads)','Publicidad exterior (OOH)','Televisión','Radio','Prensa / revistas','Punto de venta','Email marketing','Influencers / colaboraciones']},
      {id:'c8',type:'check',label:'¿Qué piezas necesitáis producir?',
        options:['Spot de vídeo','Reels / vídeos cortos','Banners digitales','Cartelería exterior','Anuncio de prensa','Piezas para redes sociales','Landing page de campaña','Emailings','Material punto de venta','Cuña de radio']},
      {id:'c9',type:'check',label:'¿Qué tono comunicativo buscáis?',
        options:['Emocional / empático','Racional / informativo','Humor / desenfadado','Aspiracional / inspirador','Provocador / rupturista','Cercano / conversacional','Corporativo / serio']},
      {id:'c10',type:'textarea',label:'¿Hay alguna campaña o referente creativo que os inspire?',
        placeholder:'La campaña X de Nike, o algo parecido al tono de la marca Y...'},
      {id:'c11',type:'radio',label:'Presupuesto de producción orientativo (sin incluir medios)',
        options:['Menos de 5.000 €','Entre 5.000 y 20.000 €','Entre 20.000 y 50.000 €','Más de 50.000 €','Prefiero no indicarlo ahora']},
      {id:'c12',type:'text',label:'¿Cuándo debería estar activa la campaña?',
        placeholder:'Lanzamiento 1 de septiembre, activa 6 semanas...'}
    ]
  },
  digital: {
    label:'Redes sociales y presencia digital', icon:'◈', questions:[
      {id:'d1',type:'check',label:'¿En qué redes sociales estáis presentes o queréis estarlo?',
        options:['Instagram','LinkedIn','TikTok','X (Twitter)','YouTube','Facebook','Pinterest','Otras']},
      {id:'d2',type:'radio',label:'Estado actual de vuestros perfiles',
        options:['Activos y con contenido regular','Activos pero sin actividad constante','Creados pero sin uso','No tenemos perfiles todavía']},
      {id:'d3',type:'check',label:'¿Cuál es el objetivo en redes sociales?',
        options:['Construir comunidad','Generar tráfico a la web','Generar leads / ventas','Employer branding / captación de talento','Thought leadership / autoridad de sector','Atención al cliente']},
      {id:'d4',type:'radio',label:'¿Qué frecuencia de publicación estimáis necesaria?',
        options:['1-2 publicaciones por semana','3-4 publicaciones por semana','Publicación diaria','No lo tenemos claro todavía']},
      {id:'d5',type:'check',label:'¿Con qué recursos internos contáis?',
        options:['Fotógrafo / videógrafo','Diseñador','Redactor / copywriter','Community manager','Sin equipo, lo externalizamos todo','Equipo parcial que necesita apoyo']},
      {id:'d6',type:'check',label:'¿Qué métricas son prioritarias?',
        options:['Seguidores / alcance','Engagement (interacciones)','Tráfico a la web','Leads generados','Ventas directas','Reconocimiento de marca']},
      {id:'d7',type:'radio',label:'¿El presupuesto incluye paid social (publicidad en redes)?',
        options:['Sí, queremos incluir inversión en medios','Solo gestión orgánica por ahora','No lo hemos decidido']},
      {id:'d8',type:'textarea',label:'¿Hay perfiles de referencia que sigáis o que os gusten?',
        placeholder:'@marca_x por su consistencia visual, @marca_y por su tono de comunicación...'}
    ]
  },
  contenidos: {
    label:'Producción de contenidos', icon:'⬡', questions:[
      {id:'con1',type:'check',label:'¿Qué tipo de contenido necesitáis producir?',
        hint:'Selecciona todo lo que aplique',
        options:['Fotografía de producto','Fotografía lifestyle / ambientada','Fotografía corporativa (equipo, oficinas)','Fotografía de eventos','Vídeo: reels / contenido redes','Vídeo: spot publicitario','Vídeo: testimoniales / casos de éxito','Vídeo: corporativo / institucional','Diseño gráfico (carruseles, infografías, banners)','Ilustración','Generación de imágenes con IA']},
      {id:'con2',type:'radio',label:'¿Podéis estar presentes durante el rodaje o shooting?',
        hint:'Afecta a logística, desplazamientos y posibilidad de ajustes en tiempo real',
        options:['Sí, sin problema','Sí, con disponibilidad limitada','No, lo gestionáis vosotros','Depende de las fechas']},
      {id:'con3',type:'textarea',label:'Si necesitáis fotografía: ¿dónde, con modelos, qué localizaciones?',
        placeholder:'Shooting en nuestras instalaciones, necesitamos modelo femenino 30-40 años...'},
      {id:'con4',type:'textarea',label:'Si necesitáis vídeo: ¿duración estimada, plataforma destino y estilo?',
        placeholder:'Reels 15-30 segundos para Instagram, tono dinámico y urbano...'},
      {id:'con5',type:'radio',label:'¿Estáis interesados en producción con IA generativa?',
        options:['Sí, queremos explorar esta opción','Sí, como complemento a producción real','No, preferimos producción tradicional','No lo hemos contemplado todavía']},
      {id:'con6',type:'radio',label:'¿Vuestro sector tiene restricciones sobre uso de imágenes generadas por IA?',
        hint:'Sectores como farmacéutico, financiero o legal pueden tener limitaciones legales o de reputación',
        options:['No, sin restricciones conocidas','Sí, hay restricciones que debemos considerar','No estamos seguros, lo verificaremos','No aplica']},
      {id:'con7',type:'check',label:'Si usáis IA generativa, ¿para qué uso principalmente?',
        options:['Redes sociales y contenido digital','Campañas publicitarias','Web y landings','Presentaciones internas','Ilustraciones de marca','Moodboards y conceptualización']},
      {id:'con8',type:'radio',label:'¿Qué volumen de producción estimáis?',
        options:['Proyecto puntual (pack de activos)','Producción mensual recurrente','Producción por campañas','Gran volumen / flujo continuo','No lo sé todavía']},
      {id:'con9',type:'textarea',label:'Referencias visuales o estéticas que os orienten',
        placeholder:'Nos gusta el estilo de @marca_x, o la estética de la campaña Y...'},
      {id:'con10',type:'radio',label:'¿Cómo queréis gestionar los derechos de los materiales?',
        options:['Cesión total de derechos (uso exclusivo)','Licencia limitada en tiempo o territorio','Uso en medios pagados (paid media)','Solo uso interno y redes propias','No lo hemos definido todavía']}
    ]
  }
};


export default MODULES;
